spring:
  datasource:
    url: jdbc:mysql://localhost:3307/wjytest?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

ssh:
  forward:
    enabled: true
    host: localhost
    port: 22
    username: root
    password: no_bug123
    from_host: localhost
    from_port: 3307
    to_host: 8.131.239.72
    to_port: 3306

server:
  port: 8888

mybatis-plus:
  configuration:
    use-generated-keys: true #更新或插入数据返回时，主键一起返回
